services:
  server:
    build:
      context: ./server
      dockerfile: ./py.Dockerfile
    volumes:
      - "./server:/server"
    container_name: server
    environment:
      - "FLASK_APP=src/main.py"
      - "FLASK_RUN_HOST=0.0.0.0"
      - "FLASK_RUN_PORT=5000"
      - "FLASK_ENV=development"
      - "DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres"
      - "DATABASE_LOG=True"
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
    tty: true
  client:
    build:
      context: ./client
      dockerfile: ./client.Dockerfile
    volumes:
      - "./client:/client"
    container_name: client
    ports:
      - "8000:8000"
    depends_on:
      - "server"
  postgres:
    build:
      context: ./database
      dockerfile: ./db.Dockerfile
    container_name: postgres
    volumes:
      - "./database/data:/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    container_name: redis
    image: "redis:latest"
  nginx:
    container_name: nginx
    image: "nginx:latest"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "7070:7070"
    depends_on:
      - "server"
      - "client"
      - "postgres"
      - "redis"
# todo: make networking explicit
