version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: ./py.Dockerfile
    volumes:
      - "./server:/server"
    environment:
      - "FLASK_APP=src/main.py"
      - "FLASK_RUN_HOST=0.0.0.0"
      - "FLASK_RUN_PORT=5000"
      - "FLASK_ENV=development"
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
    tty: true
  client:
    build:
      context: ./client
      dockerfile: ./client.Dockerfile
    volumes:
      - "./client:/client"
    ports:
      - "8000:8000"
    depends_on:
      - "server"
  postgres:
    build:
      context: ./database
      dockerfile: ./db.Dockerfile
    volumes:
      - "./database/data:/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    image: "redis:latest"
  nginx:
    image: "nginx:latest"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
# todo: make networking explicit
