version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: ./py.Dockerfile
    volumes:
      - "./server:/server"
    environment:
      - "FLASK_APP=src/main.py"
    ports:
      - "8081:8081"
    depends_on:
      - "postgres"
  client:
    build:
      context: ./client
      dockerfile: ./client.Dockerfile
    volumes:
      - "./client:/client"
    ports:
      - "8000:8000"
    depends_on:
      - "server"
  postgres:
    build:
      context: ./database
      dockerfile: ./db.Dockerfile
    volumes:
      - "./database/data:/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    image: "redis:latest"
# todo: make networking explicit
