services:
  server:
    build:
      context: ./server
      dockerfile: ./py.Dockerfile
    volumes:
      - "./server:/server"
    container_name: server
    environment:
      - "FLASK_APP=src/main.py"
      - "FLASK_RUN_HOST=0.0.0.0"
      - "FLASK_RUN_PORT=5000"
      - "FLASK_ENV=development"
      - "DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres"
      - "DATABASE_LOG=True"
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
    tty: true
  client:
    build:
      context: ./client
      dockerfile: ./client.Dockerfile
    entrypoint: npm run-script start
    environment:
      - "NODE_ENV=development"
      - "DEPLOYMENT_ENDPOINT=localhost"
    volumes:
      - "./client:/client"
      - "/client/node_modules"
    container_name: client
    ports:
      - "8000:8000"
    depends_on:
      - "server"
  postgres:
    build:
      context: ./database
      dockerfile: ./db.Dockerfile
    container_name: postgres
    volumes:
      - "./database/data:/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    container_name: redis
    image: "redis:latest"
    expose:
      - "6379"
  nginx:
    container_name: nginx
    image: "nginx:latest"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "7070:7070"
    depends_on:
      - "server"
      - "client"
      - "postgres"
      - "redis"
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - 8888:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres:5432
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter
# todo: make networking explicit
